<template>
  <div class="marketing-scroll">
    <section class="marketing-page-hero"><div class="marketing-container marketing-narrow"><p class="marketing-kicker">Privacy</p><h1>Only the data the service needs.</h1><p class="marketing-lede">A concise account of information handled by the hosted Note Colab service.</p></div></section>
    <div class="marketing-container marketing-narrow marketing-page-content">
      <section class="prose-section"><h2>Content and metadata</h2><p>Current Note Colab clients encrypt stored Markdown, titles, and supported images before upload. The hosted service stores that ciphertext. The service can see operational metadata such as share and room identifiers, access modes, timestamps, expiry, storage sizes, collaborator identifiers, image filenames, and MIME types.</p><p>Live collaboration text and collaborator state are visible to the relay while a room is active. Older share records may contain a plaintext title until an owner opens or updates them with a current client.</p></section>
      <section class="prose-section"><h2>Accounts and credentials</h2><p>The plugin can create an identity without an email address. The service stores a one-way hash of the plugin API key and the public half of the identity key pair. If you choose a public username, it is visible to the service and to people sharing an authorized room with you.</p><p>If you configure web access, the service stores a password hash, vault-key derivation salt, and hashes of independent browser-session credentials. The browser keeps its raw credential locally and the derived vault key for the tab session.</p><p>If the hosted service offers provider sign-in, it stores the provider name and stable public subject identifier linked to your Note Colab account. It does not use an email address as account identity and does not retain the provider access token. Provider sign-in authenticates the account but cannot derive your vault key or recover a plugin encryption key.</p></section>
      <section class="prose-section"><h2>Service operation</h2><p>Request data needed to run and protect the service may include IP addresses, timestamps, response status, and rate-limit state. Note Colab does not add advertising or product analytics telemetry to the plugin.</p><p>Data remains until it is deleted by the relevant product action, expires under a configured share policy, or ages out of service backups. Revoking a share disables server access but cannot delete copies already made by a recipient.</p></section>
      <section class="prose-section"><h2>Your choices</h2><ul><li>Use link expiry and revoke links that are no longer needed.</li><li>Leave the public username blank if you do not want a recognizable name shown to collaborators.</li><li>Use a compatible server you trust instead of the hosted service.</li><li>Do not share complete note links, API keys, or recovery material with unintended recipients.</li></ul></section>
      <div class="marketing-callout"><h3>Operator and privacy questions</h3><p>The hosted service at notecolab.com is operated by <a href="https://felixmrak.com">Felix Mrak</a>. Contact <a href="mailto:contact@felixmrak.com">contact@felixmrak.com</a> for support, privacy questions, or account-data requests. Self-hosted servers have their own operators and policies.</p><p>Read <NuxtLink to="/security">Security</NuxtLink> for the trust boundary. Use <a href="https://github.com/felixleopold/notecolab/issues">GitHub issues</a> for reproducible bugs and feature requests, without private content or credentials.</p></div>
    </div>
    <MarketingFooter />
  </div>
</template>

<script setup lang="ts">
useHead({ title: 'Privacy | Note Colab', meta: [{ name: 'description', content: 'What data the hosted Note Colab service handles and the controls available to users.' }] })
</script>
